### ISSUE TITLE
Feature request: Make ; optional for last statement

### ISSUE THREAD

**Issue by bluec0re** [googleprojectzero/weggli#15]
Would be nice if weggli could automatically add `;` if missing/the query is invalid:

# Current behavior
```
$ weggli `strcat()` .
Error! Query parsing failed: strcat()
```

# Wanted behavior 
```
$ weggli `strcat()` .
# same output as if strcat(); was used
```

**Comment by felixwilhelm** [comment]
This was pretty easy to implement and hopefully improves the initial user experience a bit.
