### ISSUE TITLE
'not a valid query variable' when NOT is added

### ISSUE THREAD

**Issue by PeiweiHu** [googleprojectzero/weggli#23]
I am using weggli 0.2.2. 

While typing `weggli -R'f=alloc' -R'r=free'  '{ $f($v); $r($v); }' ./`, it works. 
While typing  `weggli -R'f=alloc' -R'r=free'  '{ $f($v); NOT: $r($v); }' ./`, I got reponse saying` 'r' is not a valid query variable`

**Comment by felixwilhelm** [comment]
Hey,

thanks for the bug report and using weggli. This took a bit longer than expected, but it's now fixed with 545bf4f.
