### ISSUE TITLE
Grammar source

### ISSUE THREAD

**Issue by arlencox** [googleprojectzero/weggli#24]
In implementation details it says that

> Search queries are first parsed using an extended version of the corresponding grammar

However, `third_party/grammars/{c,cpp}/*` only contains the tree-sitter-generated C and C++ code.  Can the modified tree-sitter js grammar file be added to the repository?

**Comment by felixwilhelm** [comment]
Hi Arlen,

sorry for the delay. I've added the modified grammar.js file in 5508187.
It's a single line change to add support for '$' in identifiers.

**Comment by calixteman** [comment]
You could do something similar to:
https://github.com/mozilla/rust-code-analysis/blob/master/tree-sitter-mozcpp/grammar.js#L1
and then add your own stuff.

**Comment by felixwilhelm** [comment]
Thanks @calixteman. That looks like a much nicer approach! :)
