### ISSUE TITLE
Query returns the same result multiple times

### ISSUE THREAD

**Issue by mvanotti** [googleprojectzero/weggli#3]
I am running the following query:

```
weggli -X '{
  if (_ && _($atomic++)) { _; }
}' ~/fuchsia/zircon
```

And I am seeting the same result repeated multiple times.

You can try this by yourself running it against Fuchsia's source tree: https://cs.opensource.google/fuchsia/fuchsia

Attached screenshot of how it looks:

![image](https://user-images.githubusercontent.com/696185/135668923-a809f5bd-69d3-4100-afc5-8048bc1987b9.png)

Is this expected behavior? It feels like maybe the last _ is matching different nodes in the AST?

**Comment by mvanotti** [comment]
Note that this is fixed with the `--limit` argument, but it feels like the `--limit` is for a different use case.

**Comment by felixwilhelm** [comment]
Hi Marco,

thanks for the bug report. 
There are two issues here: 
1. if (foo) {_;} matches on all the sub nodes in the if body so you get a lot of identical results. 434d3a3 adds a deduplication step so you only get one result printed.
2. While implementing this, I realized that the {_;} pattern adds unnecessary work. 4be99e3 fixes the handling of empty compound statements so if you are not interested in the body you can just use {} now.
