### ISSUE TITLE
ANSI encoded copyright symbol in comment breaks search

### ISSUE THREAD

**Issue by SlidyBat** [googleprojectzero/weggli#8]
I have some files where there is a copyright symbol in the comments at the top of the file. It seems weggli can't handle these and just stops the search for the file entirely.

Minimal example:
```cpp
// ©

void MyBuggyFunction( void* data )
{
	char buf[10];
	memcpy( buf, data, 20 );
}
```
Result:
![image](https://user-images.githubusercontent.com/25954912/136891488-6ca7f9c3-0117-402a-b916-803ff9f7d6f2.png)

Without the copyright symbol, the search works as expected:
![image](https://user-images.githubusercontent.com/25954912/136891545-e772de2c-a3b4-4338-b314-5103612ad42d.png)

Also should note that this symbol only breaks when it is represented with the ANSI encoding (ie. 0xA9 byte), when copying the code above it will probably be represented with the UTF-8 encoding, which does work correctly.
To make reproducing this easier, I've attached the file with the ANSI encoded copyright symbol.

[test.zip](https://github.com/googleprojectzero/weggli/files/7326886/test.zip)

**Comment by felixwilhelm** [comment]
Thanks for trying out weggli and the nice bug report.
bb8e5fa95 should fix this.
